/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserProfile;
import java.util.*;
/**
 *
 * @author Boochi
 */
public class MovieDatabaseGUI extends javax.swing.JFrame {

    /**
     * Creates new form MovieDatabaseGUI
     */
    profile currentUser;
    ArrayList<profile> users = new ArrayList();
    public MovieDatabaseGUI() {
        initComponents();
        ReviewPanel.setVisible(false);
        NewUserPanel.setVisible(false);
        InvalidLoginLabel.setVisible(false);
    }
    private profile hasUser(String username)
    {
        for(profile p: users)
        {
            if(p.getUsername().equals(username))
                return p;
        }
        return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        LoginTitleLabel = new javax.swing.JLabel();
        LoginUsernameLabel = new javax.swing.JLabel();
        LoginPasswordLabel = new javax.swing.JLabel();
        LoginUsernameTextField = new javax.swing.JTextField();
        LoginPasswordTextField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        NewUserButton = new javax.swing.JButton();
        InvalidLoginLabel = new javax.swing.JLabel();
        ReviewPanel = new javax.swing.JPanel();
        SubmitButton = new javax.swing.JButton();
        MovieTitleTextField = new javax.swing.JTextField();
        MovieTitleLabel = new javax.swing.JLabel();
        FeedbackLabel = new javax.swing.JLabel();
        NewUserPanel = new javax.swing.JPanel();
        NewProfileLabel = new javax.swing.JLabel();
        NewUsernameLabel = new javax.swing.JLabel();
        PasswordLabel1 = new javax.swing.JLabel();
        NewUsernameTextField = new javax.swing.JTextField();
        NewPasswordField1 = new javax.swing.JPasswordField();
        CreateProfileButton = new javax.swing.JButton();
        PasswordLabel2 = new javax.swing.JLabel();
        NewPasswordField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MovieDatabase");

        LoginTitleLabel.setText("LOGIN");

        LoginUsernameLabel.setText("Username");

        LoginPasswordLabel.setText("Password");

        LoginPasswordTextField.setText("jPasswordField1");

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        NewUserButton.setText("New User?");
        NewUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewUserButtonActionPerformed(evt);
            }
        });

        InvalidLoginLabel.setText("INVALID USERNAME/PASSWORD!");

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LoginPasswordLabel)
                            .addComponent(LoginUsernameLabel))
                        .addGap(102, 102, 102)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LoginPasswordTextField)
                            .addComponent(LoginUsernameTextField)))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(InvalidLoginLabel)
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addComponent(LoginButton)
                                .addGap(18, 18, 18)
                                .addComponent(NewUserButton))))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(LoginTitleLabel)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addComponent(LoginTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginUsernameLabel)
                    .addComponent(LoginUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginPasswordLabel)
                    .addComponent(LoginPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InvalidLoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginButton)
                    .addComponent(NewUserButton))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        SubmitButton.setText("Submit!");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        MovieTitleTextField.setText("asdfasf");

        MovieTitleLabel.setText("Movie Title");

        FeedbackLabel.setText("Shit goes here....");

        javax.swing.GroupLayout ReviewPanelLayout = new javax.swing.GroupLayout(ReviewPanel);
        ReviewPanel.setLayout(ReviewPanelLayout);
        ReviewPanelLayout.setHorizontalGroup(
            ReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FeedbackLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addGroup(ReviewPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(MovieTitleLabel)
                        .addGap(30, 30, 30)
                        .addGroup(ReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MovieTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubmitButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        ReviewPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {MovieTitleTextField, SubmitButton});

        ReviewPanelLayout.setVerticalGroup(
            ReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MovieTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ReviewPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MovieTitleLabel)))
                .addGap(18, 18, 18)
                .addComponent(SubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FeedbackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(520, Short.MAX_VALUE))
        );

        NewProfileLabel.setText("Create a Profile!");

        NewUsernameLabel.setText("Username");

        PasswordLabel1.setText("Password");

        NewPasswordField1.setText("jPasswordField1");

        CreateProfileButton.setText("Create Profile");
        CreateProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateProfileButtonActionPerformed(evt);
            }
        });

        PasswordLabel2.setText("Retype Password");

        NewPasswordField2.setText("jPasswordField1");

        javax.swing.GroupLayout NewUserPanelLayout = new javax.swing.GroupLayout(NewUserPanel);
        NewUserPanel.setLayout(NewUserPanelLayout);
        NewUserPanelLayout.setHorizontalGroup(
            NewUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewUserPanelLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(NewUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewUserPanelLayout.createSequentialGroup()
                        .addGroup(NewUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CreateProfileButton)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NewUserPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(NewProfileLabel)))
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewUserPanelLayout.createSequentialGroup()
                        .addGroup(NewUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PasswordLabel1)
                            .addComponent(NewUsernameLabel)
                            .addComponent(PasswordLabel2))
                        .addGap(102, 102, 102)
                        .addGroup(NewUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NewPasswordField1)
                            .addComponent(NewUsernameTextField)
                            .addComponent(NewPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))))
        );
        NewUserPanelLayout.setVerticalGroup(
            NewUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewUserPanelLayout.createSequentialGroup()
                .addComponent(NewProfileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewUsernameLabel)
                    .addComponent(NewUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NewUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordLabel1)
                    .addComponent(NewPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NewUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordLabel2)
                    .addComponent(NewPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(CreateProfileButton)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {LoginPanel, ReviewPanel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NewUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>                        

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        //String feedback = "Review for " + "\"" + MovieTitleTextField.getText() + "\" submitted by " + UsernameTextField.getText();
        FeedbackLabel.setText("Review Submitted");
    }                                            

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        String entered = LoginUsernameTextField.getText();
        if(hasUser(entered) != null) //&& hasUser(entered).getPassword().equals(LoginPasswordTextField.getText()))
        {
            LoginPanel.setVisible(false);
            ReviewPanel.setVisible(true);
            currentUser = hasUser(entered);
        }
        else
        {
            InvalidLoginLabel.setVisible(true);
        }
    }                                           

    private void CreateProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        profile newuser = new profile(NewUsernameTextField.getText(), NewPasswordField1.getText());
        users.add(newuser);
        NewUserPanel.setVisible(false);
        LoginPanel.setVisible(true);
    }                                                   

    private void NewUserButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        LoginPanel.setVisible(false);
        NewUserPanel.setVisible(true);
  
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieDatabaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieDatabaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieDatabaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieDatabaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieDatabaseGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton CreateProfileButton;
    private javax.swing.JLabel FeedbackLabel;
    private javax.swing.JLabel InvalidLoginLabel;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel LoginPasswordLabel;
    private javax.swing.JPasswordField LoginPasswordTextField;
    private javax.swing.JLabel LoginTitleLabel;
    private javax.swing.JLabel LoginUsernameLabel;
    private javax.swing.JTextField LoginUsernameTextField;
    private javax.swing.JLabel MovieTitleLabel;
    private javax.swing.JTextField MovieTitleTextField;
    private javax.swing.JPasswordField NewPasswordField1;
    private javax.swing.JPasswordField NewPasswordField2;
    private javax.swing.JLabel NewProfileLabel;
    private javax.swing.JButton NewUserButton;
    private javax.swing.JPanel NewUserPanel;
    private javax.swing.JLabel NewUsernameLabel;
    private javax.swing.JTextField NewUsernameTextField;
    private javax.swing.JLabel PasswordLabel1;
    private javax.swing.JLabel PasswordLabel2;
    private javax.swing.JPanel ReviewPanel;
    private javax.swing.JButton SubmitButton;
    // End of variables declaration                   
}
